// Code generated by 'yaegi extract github.com/permadao/permaswap/halo/token/schema'. DO NOT EDIT.

package symbol

import (
	"github.com/permadao/permaswap/halo/token/schema"
	"reflect"
)

func init() {
	Symbols["github.com/permadao/permaswap/halo/token/schema/schema"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrInsufficientBalance": reflect.ValueOf(&schema.ErrInsufficientBalance).Elem(),
		"ErrInsufficientStake":   reflect.ValueOf(&schema.ErrInsufficientStake).Elem(),
		"ErrNegativeAmount":      reflect.ValueOf(&schema.ErrNegativeAmount).Elem(),
		"ErrNegativeFee":         reflect.ValueOf(&schema.ErrNegativeFee).Elem(),
		"ErrNilAmount":           reflect.ValueOf(&schema.ErrNilAmount).Elem(),
		"ErrTooLargeAmount":      reflect.ValueOf(&schema.ErrTooLargeAmount).Elem(),
		"ErrZeroAmount":          reflect.ValueOf(&schema.ErrZeroAmount).Elem(),

		// type definitions
		"Stake":     reflect.ValueOf((*schema.Stake)(nil)),
		"StakeInfo": reflect.ValueOf((*schema.StakeInfo)(nil)),
		"TokenInfo": reflect.ValueOf((*schema.TokenInfo)(nil)),
	}
}
