// Code generated by 'yaegi extract github.com/permadao/permaswap/logger'. DO NOT EDIT.

package symbol

import (
	"github.com/permadao/permaswap/logger"
	"reflect"
)

func init() {
	Symbols["github.com/permadao/permaswap/logger/logger"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(logger.New),
	}
}
